import Head from 'next/head'
import styles from '@/styles/Home.module.css'
import Vesting from '@/components/Vesting/Vesting'

export default function Home() {
  return (
    <>
      <Head>
        <title>Snowfall Vesting</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Vesting />
    </>
  )
}
